version: 2Add commentMore actions
updates:
  - package-ecosystem: mix
    directory: "/"
    versioning-strategy: lockfile-only
    schedule:
      interval: weekly
      day: thursday
    groups:
      production-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
