# Prometheus configuration for Foundation telemetry

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Foundation application metrics endpoint
  - job_name: 'foundation'
    static_configs:
      - targets: ['localhost:9568']
    metrics_path: '/metrics'
    
  # Additional Foundation services if running separately
  - job_name: 'foundation-cache'
    static_configs:
      - targets: ['localhost:9569']
    metrics_path: '/metrics'
    
  # JidoSystem agents
  - job_name: 'jido-agents'
    static_configs:
      - targets: ['localhost:9570']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']