groups:
  - name: foundation_alerts
    rules:
      # Cache performance alerts
      - alert: HighCacheLatency
        expr: histogram_quantile(0.95, rate(foundation_cache_duration_microseconds_bucket[5m])) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High cache latency detected"
          description: "95th percentile cache latency is {{ $value }}μs (threshold: 1000μs)"

      - alert: LowCacheHitRate
        expr: rate(foundation_cache_hit_total[5m]) / (rate(foundation_cache_hit_total[5m]) + rate(foundation_cache_miss_total[5m])) < 0.7
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 70%)"

      # Resource management alerts
      - alert: HighResourceDenialRate
        expr: rate(foundation_resource_manager_denied_total[5m]) > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High resource denial rate"
          description: "Resource denials at {{ $value }}/sec (threshold: 10/sec)"

      - alert: ResourceTokenExhaustion
        expr: foundation_resource_manager_active_tokens > 900
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Resource tokens near exhaustion"
          description: "{{ $value }} active tokens (warning at 900)"

      # System health alerts
      - alert: HighMemoryUsage
        expr: jido_system_health_sensor_memory_usage_percent > 85
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage"
          description: "Memory usage at {{ $value }}% (threshold: 85%)"

      - alert: HighProcessCount
        expr: jido_system_health_sensor_process_count > 10000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High process count"
          description: "{{ $value }} processes running (threshold: 10000)"

      # Task processing alerts
      - alert: HighTaskFailureRate
        expr: rate(jido_system_task_failed_total[5m]) / (rate(jido_system_task_completed_total[5m]) + rate(jido_system_task_failed_total[5m])) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High task failure rate"
          description: "Task failure rate is {{ $value | humanizePercentage }} (threshold: 10%)"

      - alert: SlowTaskProcessing
        expr: histogram_quantile(0.95, rate(jido_system_task_completed_duration_microseconds_bucket[5m])) > 5000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow task processing"
          description: "95th percentile task duration is {{ $value | humanizeDuration }} (threshold: 5s)"

      # Agent performance alerts
      - alert: PerformanceIssuesDetected
        expr: jido_system_performance_sensor_issues_detected > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Agent performance issues detected"
          description: "{{ $value }} performance issues detected across agents"

      - alert: CircuitBreakerOpen
        expr: foundation_circuit_breaker_state == 2
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Circuit breaker open"
          description: "Circuit breaker for {{ $labels.service }} is open"