name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    with:
      release: false
      publish-docs: false
      spark-formatter: false
      spark-cheat-sheets: false
      sobelow: false
      ash_postgres: false
      igniter-upgrade: false
      credo: false
